version: "3.8"
services:
  # Web service -- runs the web application front end
  web:
    # name alias
    image: mtumba_bay
    # build within the current directory
    build:
      context: .
    command: yarn dev
    volumes:
      # Maps project directory "./client" to working directory
      # inside the container
      - .:/usr/src/mtumba_bay
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
